-- Role: "Tourplaner_User"
-- DROP ROLE "Tourplaner_User";

CREATE ROLE "Tourplaner_User" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:N9GV3cByrOql5A7g2tBihg==$k9u/FhDOf6BAYdFCzwnUESUxtkiCcSbqjlJpyHGt9Ns=:oPtyvR6qB+QWyCGA/WwCWOIgTU7preS4ilPh0GavkkQ=';